name: Build Application

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            python-version: '3.11'
            arch: x64
            pyinstaller_target: windows-x64
          - os: windows-latest
            python-version: '3.11'
            arch: x86
            pyinstaller_target: windows-x86
          - os: ubuntu-latest
            python-version: '3.11'
            arch: x64
            pyinstaller_target: linux-x64
          - os: macos-latest
            python-version: '3.11'
            arch: x64
            pyinstaller_target: macos-x64
          - os: macos-latest
            python-version: '3.11'
            arch: arm64
            pyinstaller_target: macos-arm64
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        architecture: ${{ matrix.arch == 'x86' && matrix.os == 'windows-latest' ? 'x86' : 'x64' }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt
        
    - name: Build executable
      run: pyinstaller --onefile --name ehall-backend-${{ matrix.pyinstaller_target }} app.py

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: ehall-backend_${{ matrix.os }}-${{ matrix.arch }}
        path: dist/

